// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var masterResponse;
    masterResponse = $.ajax("http://www.omdbapi.com/?s=Matrix", {
      dataType: "json"
    });
    return masterResponse.done(function(data) {
      var imdb, li, movie, movies, _i, _len;
      movies = data.Search;
      for (_i = 0, _len = movies.length; _i < _len; _i++) {
        movie = movies[_i];
        imdb = movie.imdbID;
        li = "<li><a href='#' data-imdbid='" + imdb + "'>" + movie.Title + "</a></li>";
        console.log(li);
        $('.movies').append(li);
      }
      return $('a').click(function(e) {
        var detailResponse, imdbID;
        imdbID = $(this).data('imdbid');
        detailResponse = $.ajax("http://www.omdbapi.com/?i=" + imdbID + "&plot=full", {
          dataType: "json"
        });
        return detailResponse.done(function(data) {
          return console.log(data);
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=main.map
