// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    $('#search').on('submit', function(e) {
      var masterResponse, searchTerm;
      e.preventDefault();
      searchTerm = $('#searchField').val();
      masterResponse = $.ajax("http://www.omdbapi.com/?s=" + searchTerm, {
        dataType: "json"
      });
      return masterResponse.done(function(data) {
        var detail, imdb, movie, movies, _i, _len, _results;
        movies = data.Search;
        _results = [];
        for (_i = 0, _len = movies.length; _i < _len; _i++) {
          movie = movies[_i];
          imdb = movie.imdbID;
          detail = $.ajax("http://www.omdbapi.com/?i=" + imdb, {
            dataType: 'json'
          });
          _results.push(detail.done(function(movie) {
            var rating;
            rating = movie.imdbRating;
            rating = parseFloat(movie.imdbRating);
            if (rating <= 2) {
              return $('.nope').append("<li>" + movie.Title + "</li>");
            } else if (rating <= 4) {
              return $('.meh').append("<li>" + movie.Title + "</li>");
            } else if (rating <= 6) {
              return $('.ok').append("<li>" + movie.Title + "</li>");
            } else if (rating <= 8) {
              return $('.veryGood').append("<li>" + movie.Title + "</li>");
            } else {
              return $('.fantastic').append("<li>" + movie.Title + "</li>");
            }
          }));
        }
        return _results;
      });
    });
    return $('#reset').click(function() {
      return $('.movieColumns li').html("");
    });
  });

}).call(this);

//# sourceMappingURL=main.map
